"""add apple user id attribute

Revision ID: 7801289cdd22
Revises: 43acb9f30079
Create Date: 2024-11-12 16:30:13.104549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7801289cdd22'
down_revision = '43acb9f30079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_user_id', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['apple_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apple_user_id')

    # ### end Alembic commands ###
